apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: devops-info-service-set
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            namespace: dev
            valuesFile: values-dev.yaml
          - env: prod
            namespace: prod
            valuesFile: values-prod.yaml
  template:
    metadata:
      name: 'devops-info-service-{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/peplxx/DevOps-Core-Course.git
        targetRevision: feat/lab13
        path: project/k8s/devops-info-service
        helm:
          releaseName: '{{env}}'
          valueFiles:
            - values.yaml
            - '{{valuesFile}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
