apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-info-service-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/peplxx/DevOps-Core-Course.git
    targetRevision: feat/lab13
    path: project/k8s/devops-info-service
    helm:
      releaseName: prod
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
