apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devops-info-service.fullname" . }}-config
  labels:
    {{- include "devops-info-service.labels" . | nindent 4 }}
data:
  config.json: |-
{{- .Files.Get "files/config.json" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devops-info-service.fullname" . }}-env
  labels:
    {{- include "devops-info-service.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.environment | quote }}
  LOG_LEVEL: {{ .Values.logLevel | quote }}
  APP_NAME: {{ .Values.application.name | quote }}
