apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - local.devops.com
      secretName: devops-tls
  rules:
    - host: local.devops.com
      http:
        paths:
          - path: /app1
            pathType: Prefix
            backend:
              service:
                name: devops-info-service
                port:
                  number: 80
          - path: /app2
            pathType: Prefix
            backend:
              service:
                name: devops-info-service-v2
                port:
                  number: 80
