---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags: common

- name: Install common packages
  apt:
    name: "{{ common_packages }}"
    state: present
    update_cache: yes
  tags: common

- name: Set timezone
  timezone:
    name: "{{ timezone }}"
  tags: common

- name: Ensure pip is installed
  apt:
    name: python3-pip
    state: present
  tags: common
