apiVersion: v2
name: devops-info-service
description: A Helm chart for the DevOps Info Service Python application
type: application
version: 0.2.0
appVersion: "1.0.0"

keywords:
  - python
  - web
  - devops

maintainers:
  - name: Your Name
    email: your.email@example.com

sources:
  - https://github.com/yourusername/DevOps-Core-Course
