replicaCount: 3

image:
  repository: peplxx/devops-info-service
  tag: "latest"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30080

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001

application:
  host: "0.0.0.0"
  port: 5000

credentials:
  username: changeme-user
  password: changeme-password

serviceAccount:
  create: true
  name: ""

vaultInjector:
  enabled: false
  role: devops-info-service
  secretPath: secret/data/devops-info/config
  useCustomTemplate: false

livenessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
